// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJz47apkySYRsRb0VOt1mkOmfY8BlHUNQ',
    appId: '1:124168543549:web:2a701b76d49d6f13b9b954',
    messagingSenderId: '124168543549',
    projectId: 'myproject-bcd7d',
    authDomain: 'myproject-bcd7d.firebaseapp.com',
    storageBucket: 'myproject-bcd7d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiIphwk6iSGxVwi3m7JKW2hV64yvYCb2A',
    appId: '1:124168543549:android:a3221c8c4ae861b4b9b954',
    messagingSenderId: '124168543549',
    projectId: 'myproject-bcd7d',
    storageBucket: 'myproject-bcd7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjfOzGA8qk75CLelOboQqpupjlxc4Kf2M',
    appId: '1:124168543549:ios:fc666711de45f876b9b954',
    messagingSenderId: '124168543549',
    projectId: 'myproject-bcd7d',
    storageBucket: 'myproject-bcd7d.firebasestorage.app',
    iosBundleId: 'com.example.untitled18',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjfOzGA8qk75CLelOboQqpupjlxc4Kf2M',
    appId: '1:124168543549:ios:fc666711de45f876b9b954',
    messagingSenderId: '124168543549',
    projectId: 'myproject-bcd7d',
    storageBucket: 'myproject-bcd7d.firebasestorage.app',
    iosBundleId: 'com.example.untitled18',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJz47apkySYRsRb0VOt1mkOmfY8BlHUNQ',
    appId: '1:124168543549:web:fc754668ac71dc4bb9b954',
    messagingSenderId: '124168543549',
    projectId: 'myproject-bcd7d',
    authDomain: 'myproject-bcd7d.firebaseapp.com',
    storageBucket: 'myproject-bcd7d.firebasestorage.app',
  );
}
